#
# Copyright (c) 2007-2013 Artigile.
# Software development company.
# All Rights Reserved.
#
# This software is the confidential and proprietary information of Artigile. ("Confidential Information").
# You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the
# license agreement you entered into with Artigile software company.
#

google.api.client.id = ${maven.google.api.client.id}
google.api.client.secret =${maven.google.api.client.secret}
phone.api.key = ${maven.phone.api.key}